### PR TITLE
escape single quotes for replaygain shell command

### PR DESCRIPTION
**Pull request by robinwils**
consider shlex for python3 (https://docs.python.org/dev/library/shlex.html#shlex.quote) ?

Issue #27

### CODE REVIEW

**Comment by RecursiveForest** [comment]
This won't fix the problem if you are in a subdir, but if you add escape_quote to the relevant line (# 177) I'll merge.

**Comment by RecursiveForest** [comment]
I will also accept a patch that uses shlex.quote() in escape_quote or replaces escape_quote with shlex.quote() (the latter being preferable). However, if you don't do this, I will this weekend, along with some PEP8-y style changes.

**Comment by robinwils** [comment]
Alright. I tried just replacing escape_quote with shlex.quote but it isn't that simple apparently

**Comment by RecursiveForest** [comment]
Can you not include the aac/m4a/ffmpeg stuff? I have no problem accepting it but it doesn't belong in this PR, and I want to be able to quickly read the short versions of commit messages to understand history.

**Comment by robinwils** [comment]
You mean the file extensions stuff ?
The script cannot convert to alac, or replay gain on aac  otherwise on my end

**Comment by robinwils** [comment]
OK I removed it, can you squash when merging ?

**Comment by robinwils** [comment]
Any news on this ?

**Comment by RecursiveForest** [comment]
Your patch introduced regressions in character escaping and I haven't had the time expected to look at it yet.

**Comment by RecursiveForest** [comment]
And regarding aac/m4a, I am happy to accept a patch, just make a new PR.

**Pull request closed without merging**
